# Site wide configuration

title: Requestly
locale: en_US
description: Chrome Extension to modify HTTP(s) Requests
logo: site-logo.png
search: true
env: prod
baseurl: /public
url: http://requestly.github.io
chrome_store_url: http://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["misc", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sachin Jain
  avatar: bio-photo-sachin.jpg
  email: sachinjain024@gmail.com
  disqus-shortname: requestly
  twitter: #sachinjain024
  facebook: #sachinjain024
  github: #blunderboy
  stackexchange: #http://stackoverflow.com/users/816213/blunderboy
  linkedin: #sachinjain024
  google:
    plus: #sachinjain024
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
